name: Release finish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version to finish"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get -y install git-flow

      - name: Set up Node.js
        uses: actions/setup-node@v1.2.0
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@cytiva"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: release/${{ github.event.inputs.version }}
          fetch-depth: 0
          token: ${{ secrets.SUPER_AUTH_TOKEN }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "Release manager"
          git config user.email noreply@github.com

      - name: Init git flow
        run: |
          git checkout master
          git checkout develop
          git checkout release/${{ github.event.inputs.version }}
          git flow init -d

      - name: Bump package.json version to release
        run: |
          npm version --git-tag-version=false ${{ github.event.inputs.version }}

      - name: Commit changes
        run: |
          git commit -a -m "ci: version bump to ${{ github.event.inputs.version }}"

      - name: Release finish
        run: |
          git flow release finish ${{ github.event.inputs.version }} -m "chore: version bumped" ${{ github.event.inputs.version }}

      - name: Release publish
        run: |
          git push --all --follow-tags --no-verify
